{% set name = "pyglove" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/pyglove/archive/v{{ version }}.tar.gz
  sha256: e8670b78013121f2710e17c5ca4f6de2968d47c1e16568db6b463049c3f0e1c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docstring_parser >=0.12

test:
  imports:
    - pyglove
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/pyglove
  summary: General-purpose library for Python object manipulation.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
