{% set name = "pyglove" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/pyglove/archive/v{{ version }}.tar.gz
  sha256: 40a0410c9cc03897b7200470cc6ed02e3f124137a6da9ed6ec04d549801789ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docstring_parser >=0.12

test:
  imports:
    - pyglove
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/pyglove
  summary: General-purpose library for Python object manipulation.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
